CREATE TABLE companies (
    company_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_name VARCHAR(255) NOT NULL,
    cnpj VARCHAR(32),
    description VARCHAR(1000),
    company_email VARCHAR(255),
    company_phone_number VARCHAR(32),
    business_area VARCHAR(255)
);

CREATE TABLE leads (
    lead_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES companies (company_id),
    is_lead BOOLEAN NOT NULL DEFAULT TRUE,
    phone_number VARCHAR(32),
    email VARCHAR(255),
    date DATE,
    comunication_channel VARCHAR(255),
    agent_name VARCHAR(255),
    location VARCHAR(255),
    offer VARCHAR(1000)
);

CREATE TABLE client_entity (
    client_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES companies (company_id),
    lead_id BIGINT REFERENCES leads (lead_id)
);

CREATE TABLE lead_tasks (
    lead_task_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lead_id BIGINT NOT NULL REFERENCES leads (lead_id),
    agent_name VARCHAR(255),
    place VARCHAR(255),
    contact_method VARCHAR(255),
    meeting_location VARCHAR(255),
    proposal VARCHAR(1000),
    feedback VARCHAR(1000),
    lead_task_status VARCHAR(32) NOT NULL DEFAULT 'EM_PROCESSO'
);

CREATE TABLE client_tasks (
    task_client_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id BIGINT NOT NULL REFERENCES clients (client_id),
    meeting_topic VARCHAR(255),
    task_begin DATE,
    task_end DATE,
    project_description VARCHAR(1000),
    notes VARCHAR(2000)
);
