spring.application.name=app-resource-api

server.port=8081

# application.properties
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080

# Database R2DBC Configuration
spring.r2dbc.url=r2dbc:postgresql://localhost:5432/hermecarddb
spring.r2dbc.username=${DB_USERNAME:postgres}
spring.r2dbc.password=${DB_PASSWORD:NeverEndingWar64}

# Redis Configuration
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
