server:
  port: 8082

spring:
  application:
    name: app-gateway
  data:
    redis:
      host: localhost
      port: 6379
      password:
      database: 0

services:
  auth-api:
    uri: ${AUTH_API_URL:http://localhost:8080}
  resource-api:
    uri: ${RESOURCE_API_URL:http://localhost:8081}