-- Tabela de usuários
CREATE TABLE users (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       username VARCHAR(255) NOT NULL UNIQUE,
                       password VARCHAR(255) NOT NULL,
                       role VARCHAR(255) NOT NULL,
                       firstname VARCHAR(255) NOT NULL,
                       lastname VARCHAR(255) NOT NULL,
                       email VARCHAR(255) NOT NULL UNIQUE,
                       emailverified BOOLEAN NOT NULL DEFAULT FALSE,
                       enabled BOOLEAN NOT NULL DEFAULT TRUE,
                       accountlocked BOOLEAN NOT NULL DEFAULT FALSE,
                       createdat TIMESTAMP,
                       updatedat TIMESTAMP,
                       phonenumber VARCHAR(255),
                       phoneverified BOOLEAN NOT NULL DEFAULT FALSE,
                       pictureurl VARCHAR(255),
                       locale VARCHAR(255),
                       zoneinfo VARCHAR(255)
);

-- Tabela de clients OAuth2 registrados
CREATE TABLE oauth2_registered_client (
                                          id VARCHAR(255) PRIMARY KEY,
                                          clientid VARCHAR(100) NOT NULL,
                                          clientidissuedat TIMESTAMP,
                                          clientsecret VARCHAR(200),
                                          clientsecretexpiresat TIMESTAMP,
                                          clientname VARCHAR(200),
                                          clientauthenticationmethods VARCHAR(1000) NOT NULL,
                                          authorizationgranttypes VARCHAR(1000) NOT NULL,
                                          redirecturis VARCHAR(1000),
                                          postlogoutredirecturis VARCHAR(1000),
                                          scopes VARCHAR(1000) NOT NULL,
                                          clientsettings VARCHAR(2000) NOT NULL,
                                          tokensettings VARCHAR(2000) NOT NULL
);

-- Tabela de autorizações OAuth2 (codes, tokens, etc)
CREATE TABLE oauth2_authorization (
                                      id VARCHAR(255) PRIMARY KEY,
                                      registeredclientid VARCHAR(100) NOT NULL,
                                      principalname VARCHAR(200) NOT NULL,
                                      authorizationgranttype VARCHAR(100) NOT NULL,
                                      authorizedscopes VARCHAR(1000),
                                      attributes VARCHAR(4000),
                                      state VARCHAR(500),

                                      authorizationcodevalue VARCHAR(4000),
                                      authorizationcodeissuedat TIMESTAMP,
                                      authorizationcodeexpiresat TIMESTAMP,
                                      authorizationcodemetadata VARCHAR(2000),

                                      accesstokenvalue VARCHAR(4000),
                                      accesstokenissuedat TIMESTAMP,
                                      accesstokenexpiresat TIMESTAMP,
                                      accesstokenmetadata VARCHAR(2000),
                                      accesstokentype VARCHAR(100),
                                      accesstokenscopes VARCHAR(1000),

                                      refreshtokenvalue VARCHAR(4000),
                                      refreshtokenissuedat TIMESTAMP,
                                      refreshtokenexpiresat TIMESTAMP,
                                      refreshtokenmetadata VARCHAR(2000),

                                      oidcidtokenvalue VARCHAR(4000),
                                      oidcidtokenissuedat TIMESTAMP,
                                      oidcidtokenexpiresat TIMESTAMP,
                                      oidcidtokenmetadata VARCHAR(2000),
                                      oidcidtokenclaims VARCHAR(2000),

                                      usercodevalue VARCHAR(4000),
                                      usercodeissuedat TIMESTAMP,
                                      usercodeexpiresat TIMESTAMP,
                                      usercodemetadata VARCHAR(2000),

                                      devicecodevalue VARCHAR(4000),
                                      devicecodeissuedat TIMESTAMP,
                                      devicecodeexpiresat TIMESTAMP,
                                      devicecodemetadata VARCHAR(2000)
);

-- Tabela de consentimentos de autorização
-- Nome da tabela precisa permanecer entre aspas com case exato,
-- pois a entidade usa @Table(name = "`authorizationConsent`") (backticks = quoting no Hibernate)
CREATE TABLE "authorizationConsent" (
                                        registeredclientid VARCHAR(100) NOT NULL,
                                        principalname VARCHAR(200) NOT NULL,
                                        authorities VARCHAR(1000) NOT NULL,
                                        PRIMARY KEY (registeredclientid, principalname)
);